### ISSUE TITLE
undefined local variable or method `color' for main:Object (NameError)

### ISSUE THREAD

**Issue by matheusca** [sevos/zeus-parallel_tests#14]
When I run, for example: zeus parallel_rspec spec spec/features/products.rb

I get the error:

```/var/folders/xy/659j55hs2jgc_f9kkd5yp_7h0000gn/T/rspec_args20130429-78275-1nb60kg:1:in `<top (required)>': undefined local variable or method `color' for main:Object (NameError)
	from /Users/matheus/.rvm/gems/ruby-1.9.3-p0@spree_adriinox/gems/zeus-0.13.3/lib/zeus/load_tracking.rb:50:in `load'
	from /Users/matheus/.rvm/gems/ruby-1.9.3-p0@spree_adriinox/gems/zeus-0.13.3/lib/zeus/load_tracking.rb:50:in `load'
	from /Users/matheus/.rvm/gems/ruby-1.9.3-p0@spree_adriinox/gems/zeus-0.13.3/lib/zeus/load_tracking.rb:43:in `load'
	from /Users/matheus/.rvm/gems/ruby-1.9.3-p0@spree_adriinox/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:245:in `block in load'
	from /Users/matheus/.rvm/gems/ruby-1.9.3-p0@spree_adriinox/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:236:in `load_dependency'
	from /Users/matheus/.rvm/gems/ruby-1.9.3-p0@spree_adriinox/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:245:in `load'
	from /Users/matheus/.rvm/gems/ruby-1.9.3-p0@spree_adriinox/gems/rspec-core-2.13.1/lib/rspec/core/configuration.rb:819:in `block in load_spec_files'
	from /Users/matheus/.rvm/gems/ruby-1.9.3-p0@spree_adriinox/gems/rspec-core-2.13.1/lib/rspec/core/configuration.rb:819:in `each'
	from /Users/matheus/.rvm/gems/ruby-1.9.3-p0@spree_adriinox/gems/rspec-core-2.13.1/lib/rspec/core/configuration.rb:819:in `load_spec_files'
	from /Users/matheus/.rvm/gems/ruby-1.9.3-p0@spree_adriinox/gems/rspec-core-2.13.1/lib/rspec/core/command_line.rb:22:in `run'
	from /Users/matheus/.rvm/gems/ruby-1.9.3-p0@spree_adriinox/gems/rspec-core-2.13.1/lib/rspec/core/runner.rb:80:in `run'
	from /Users/matheus/.rvm/gems/ruby-1.9.3-p0@spree_adriinox/gems/rspec-core-2.13.1/lib/rspec/core/runner.rb:17:in `block in autorun'
	from /Users/matheus/.rvm/gems/ruby-1.9.3-p0@spree_adriinox/gems/zeus-0.13.3/lib/zeus.rb:103:in `fork'
	from /Users/matheus/.rvm/gems/ruby-1.9.3-p0@spree_adriinox/gems/zeus-0.13.3/lib/zeus.rb:103:in `command'
	from /Users/matheus/.rvm/gems/ruby-1.9.3-p0@spree_adriinox/gems/zeus-0.13.3/lib/zeus.rb:80:in `block (3 levels) in go'
	from /Users/matheus/.rvm/gems/ruby-1.9.3-p0@spree_adriinox/gems/zeus-0.13.3/lib/zeus.rb:80:in `fork'
	from /Users/matheus/.rvm/gems/ruby-1.9.3-p0@spree_adriinox/gems/zeus-0.13.3/lib/zeus.rb:80:in `block (2 levels) in go'
	from /Users/matheus/.rvm/gems/ruby-1.9.3-p0@spree_adriinox/gems/zeus-0.13.3/lib/zeus.rb:73:in `each'
	from /Users/matheus/.rvm/gems/ruby-1.9.3-p0@spree_adriinox/gems/zeus-0.13.3/lib/zeus.rb:73:in `block in go'
	from /Users/matheus/.rvm/gems/ruby-1.9.3-p0@spree_adriinox/gems/zeus-0.13.3/lib/zeus.rb:62:in `loop'
	from /Users/matheus/.rvm/gems/ruby-1.9.3-p0@spree_adriinox/gems/zeus-0.13.3/lib/zeus.rb:62:in `go'
	from /Users/matheus/.rvm/gems/ruby-1.9.3-p0@spree_adriinox/gems/zeus-0.13.3/lib/zeus.rb:78:in `block (3 levels) in go'
	from /Users/matheus/.rvm/gems/ruby-1.9.3-p0@spree_adriinox/gems/zeus-0.13.3/lib/zeus.rb:78:in `fork'
	from /Users/matheus/.rvm/gems/ruby-1.9.3-p0@spree_adriinox/gems/zeus-0.13.3/lib/zeus.rb:78:in `block (2 levels) in go'
	from /Users/matheus/.rvm/gems/ruby-1.9.3-p0@spree_adriinox/gems/zeus-0.13.3/lib/zeus.rb:73:in `each'
	from /Users/matheus/.rvm/gems/ruby-1.9.3-p0@spree_adriinox/gems/zeus-0.13.3/lib/zeus.rb:73:in `block in go'
	from /Users/matheus/.rvm/gems/ruby-1.9.3-p0@spree_adriinox/gems/zeus-0.13.3/lib/zeus.rb:62:in `loop'
	from /Users/matheus/.rvm/gems/ruby-1.9.3-p0@spree_adriinox/gems/zeus-0.13.3/lib/zeus.rb:62:in `go'
	from /Users/matheus/.rvm/gems/ruby-1.9.3-p0@spree_adriinox/gems/zeus-0.13.3/lib/zeus.rb:78:in `block (3 levels) in go'
	from /Users/matheus/.rvm/gems/ruby-1.9.3-p0@spree_adriinox/gems/zeus-0.13.3/lib/zeus.rb:78:in `fork'
	from /Users/matheus/.rvm/gems/ruby-1.9.3-p0@spree_adriinox/gems/zeus-0.13.3/lib/zeus.rb:78:in `block (2 levels) in go'
	from /Users/matheus/.rvm/gems/ruby-1.9.3-p0@spree_adriinox/gems/zeus-0.13.3/lib/zeus.rb:73:in `each'
	from /Users/matheus/.rvm/gems/ruby-1.9.3-p0@spree_adriinox/gems/zeus-0.13.3/lib/zeus.rb:73:in `block in go'
	from /Users/matheus/.rvm/gems/ruby-1.9.3-p0@spree_adriinox/gems/zeus-0.13.3/lib/zeus.rb:62:in `loop'
	from /Users/matheus/.rvm/gems/ruby-1.9.3-p0@spree_adriinox/gems/zeus-0.13.3/lib/zeus.rb:62:in `go'
	from /Users/matheus/.rvm/gems/ruby-1.9.3-p0@spree_adriinox/gems/zeus-0.13.3/lib/zeus.rb:78:in `block (3 levels) in go'
	from /Users/matheus/.rvm/gems/ruby-1.9.3-p0@spree_adriinox/gems/zeus-0.13.3/lib/zeus.rb:78:in `fork'
	from /Users/matheus/.rvm/gems/ruby-1.9.3-p0@spree_adriinox/gems/zeus-0.13.3/lib/zeus.rb:78:in `block (2 levels) in go'
	from /Users/matheus/.rvm/gems/ruby-1.9.3-p0@spree_adriinox/gems/zeus-0.13.3/lib/zeus.rb:73:in `each'
	from /Users/matheus/.rvm/gems/ruby-1.9.3-p0@spree_adriinox/gems/zeus-0.13.3/lib/zeus.rb:73:in `block in go'
	from /Users/matheus/.rvm/gems/ruby-1.9.3-p0@spree_adriinox/gems/zeus-0.13.3/lib/zeus.rb:62:in `loop'
	from /Users/matheus/.rvm/gems/ruby-1.9.3-p0@spree_adriinox/gems/zeus-0.13.3/lib/zeus.rb:62:in `go'
	from -e:1:in `<main>'```

Specs passed or failed, but the error show me disrupts my tests.

**Comment by schneidmaster** [comment]
I am (as of a few days ago) the new maintainer for this gem, and I'm looking through the old issues now. Closing this issue as it seems to be resolved by @dalpo's suggestion (which is also suggested by the Zeus README).
