### ISSUE TITLE
Test integration with zeus

### ISSUE THREAD

**Issue by sevos** [sevos/zeus-parallel_tests#2]
How to test integration with [burke/zeus](https://github.com/burke/zeus)? I started playing in [smoke_tests branch](https://github.com/sevos/zeus-parallel_tests/tree/smoke_tests) but I've got following problems:

* no way to start zeus silently without fancy output
* zeus binary probably forks at start. I've got problems with intercepting PID of process to kill after test suite

**Comment by schneidmaster** [comment]
Closing as integration testing with Zeus is now working in master.
