### ISSUE TITLE
Zeus parallel_rspec fails to run do to ActiveRecord::Base:Class (NoMethodError)

### ISSUE THREAD

**Issue by saghaulor** [sevos/zeus-parallel_tests#20]
When trying to execute 

```
zeus parallel_rspec spec/lib/sso/pingfederate_spec.rb
```

> \`method_missing': undefined method `connection_config' for ActiveRecord::Base:Class (NoMethodError)

Additionally, there are Ruby processes that continue to run and use up to 100% CPU. I have to manually kill them.

**Comment by schneidmaster** [comment]
I am (as of a few days ago) the new maintainer for this gem, and I'm looking through the old issues now. Closing this issue as it does not seem to be a bug with zeus-parallel_tests.
