### ISSUE TITLE
Support guard-rspec (4.0.4)

### ISSUE THREAD

**Issue by maxcal** [sevos/zeus-parallel_tests#26]
In later versions of guard-rspec the `zeus`, `bundle` and `parallel` options are depreciated:

`Guard::RSpec DEPRECATION WARNING: The :zeus option is deprecated. Please customize the new :cmd option to fit your need.`

However if I invoke rspec_parallel in my Guardfile 

```
guard :rspec, cmd: 'zeus parallel_rspec' do
  #...
end
```

It fails as Guard appends the -f argument. 

```
/Users/maxcal/.rvm/gems/ruby-2.0.0-p247@remote-wind/gems/parallel_tests-0.16.10/lib/parallel_tests/cli.rb:146:in `parse_options!': invalid option: -f (OptionParser::InvalidOption)
	from /Users/maxcal/.rvm/gems/ruby-2.0.0-p247@remote-wind/gems/parallel_tests-0.16.10/lib/parallel_tests/cli.rb:8:in `run'
	from /Users/maxcal/.rvm/gems/ruby-2.0.0-p247@remote-wind/gems/parallel_tests-0.16.10/bin/parallel_rspec:5:in `<top (required)>'
	from /Users/maxcal/.rvm/gems/ruby-2.0.0-p247@remote-wind/bin/parallel_rspec:23:in `load'
	from /Users/maxcal/.rvm/gems/ruby-2.0.0-p247@remote-wind/bin/parallel_rspec:23:in `<main>'
	from /Users/maxcal/.rvm/gems/ruby-2.0.0-p247@remote-wind/bin/ruby_executable_hooks:15:in `eval'
	from /Users/maxcal/.rvm/gems/ruby-2.0.0-p247@remote-wind/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by schneidmaster** [comment]
I am (as of a few days ago) the new maintainer for this gem, and I'm looking through the old issues now. Do you still need to use the workaround you mentioned? If so, I'll add it to my queue to develop a more long-term fix. If not, feel free to close this issue.

**Comment by nathany** [comment]
I'm no longer using this gem.
