### ISSUE TITLE
The ParallelTests::RSpec::FailuresLogger formatter uses the deprecated formatter interface not supported directly by RSpec 3.

### ISSUE THREAD

**Issue by ijcd** [sevos/zeus-parallel_tests#31]
Deprecation Warnings:

 The ParallelTests::RSpec::FailuresLogger formatter uses the deprecated formatter interface not supported directly by RSpec 3.  To continue to use this formatter you must install the `rspec-legacy_formatters` gem, which provides support for legacy formatters or upgrade the formatter to a compatible version.  Formatter added at: /Users/ijcd/.rvm/gems/ruby-1.9.3-p448/gems/zeus-parallel_tests-0.2.4/lib/zeus/parallel_tests/rails.rb:32:in `test'

**Comment by schneidmaster** [comment]
That is coming from parallel_tests.
