### ISSUE TITLE
simplecov coverage % different between zeus parallel_rspec spec and parallel_rspec spec

### ISSUE THREAD

**Issue by trandoanhung1991** [sevos/zeus-parallel_tests#32]
Using zeus parallel_rspec spec it's reporting a lower % of code covered compared to running parallel_rspec spec.

**Comment by edslocomb** [comment]
simplecov uses a heuristic to detect when it is being run under parallel_tests, and if detected, uses differently named output files, and merges results at the end of the run.

when zeus starts the test workers, none of the things that simplecov tries to detect are present.  (for details on the heuristic, see: https://github.com/colszowka/simplecov/pull/185/files)

If you want accurate coverage reports, you'll need to run your test suite either without zeus, or without parallel_tests.

**Comment by schneidmaster** [comment]
You can also handle this using a custom Zeus plan. Run `zeus-parallel_tests init`, which will generate `zeus.json` and `custom_plan.rb`. Then, here is an example `custom_plan.rb` that I worked out for my company's main app (which uses zeus, parallel_tests, and simplecov):

```ruby
# custom_plan.rb
require 'zeus/parallel_tests'
require 'simplecov' 
 
class CustomPlan < Zeus::ParallelTests::Rails
  def test(argv = ARGV)
    # Start SimpleCov
    SimpleCov.start

    # Run tests
    super
  end
end
 
Zeus.plan = CustomPlan.new
```

Closing issue for now, comment further if you still see problems.
