### ISSUE TITLE
Warning every time when I run parallel_tests

### ISSUE THREAD

**Issue by asiniy** [sevos/zeus-parallel_tests#33]
Hello!

I meet strange warning of this gem.

``` bash
zeus parallel_rspec spec/
4 processes for 16 specs, ~ 4 specs per process
Warning: Specifying a Rails environment via RAILS_ENV has no effect for commands run with zeus.
Warning: Specifying a Rails environment via RAILS_ENV has no effect for commands run with zeus.
Warning: Specifying a Rails environment via RAILS_ENV has no effect for commands run with zeus.
Warning: Specifying a Rails environment via RAILS_ENV has no effect for commands run with zeus.

# Implementing of tests starts here!
```

How can I avoid these warnings?

Stack:
`ubuntu 14.04`
`rvm`
`ruby 2.2.1 mri`
`rails 4.2.0`
`rspec 3.1.7`
`zeus 0.13.3`
`zeus-parallel_tests 0.2.4`

**Comment by schneidmaster** [comment]
That warning is coming from zeus (not zeus-parallel_tests); see [here](https://github.com/burke/zeus/blob/master/go/zeusclient/zeusclient.go#L34-L38). You have $RAILS_ENV being set somewhere in your environment - perhaps in your bash profile. Also, some IDEs like RubyMine will automatically set $RAILS_ENV.
