### ISSUE TITLE
update zeus version

### ISSUE THREAD

**Issue by huoshiqiu** [sevos/zeus-parallel_tests#34]
```ruby
warning: already initialized constant APP_PATH
bin/rails:2: warning: previous definition of APP_PATH was here
```

Get this problem when i install zeus-paraller_tests in my project?
maybe you should update the version of zeus

[reference this issue](https://github.com/burke/zeus/issues/304)

**Comment by schneidmaster** [comment]
I (new maintainer as of a few days ago) am actively working to update the app to support Zeus 0.15. Check back in a few weeks.
