### ISSUE TITLE
zeusclient.go:95: EOF

### ISSUE THREAD

**Issue by kyprifog** [sevos/zeus-parallel_tests#35]
I followed the installation instructions and ran 
zeus parallel_rspec spec
and received

"zeusclient.go:95: EOF"

using zeus 0.15.4

**Comment by schneidmaster** [comment]
Currently only Zeus 0.13.3 is supported. (Note that the gemspec dependency is `~> 0.13.3` - you are likely using a system Zeus that is a higher version.) I am actively working on support for 0.15.4 though.

**Comment by kyprifog** [comment]
Sorry I double checked my Gemfile.lock, I am using 0.13.3

**Comment by schneidmaster** [comment]
Can you check that the output of `zeus --version` is 0.13.3?

**Comment by kyprifog** [comment]
Yep, I did that right after I posted, was returning 0.15.4.  Uninstalled rebundled, now it works.  I'll close,  thanks!

**Comment by schneidmaster** [comment]
No worries, cheers. Check back in a few weeks (hopefully) for 0.15.4 support.
