### ISSUE TITLE
cache_store not reloading

### ISSUE THREAD

**Issue by layonferreira** [sevos/zeus-parallel_tests#38]
I'm trying to implement **zeus-parallel_tests** on a project that already works with the **parallel_tests** gem.
The problem is: the **parallel_tests**  [documentation](https://github.com/grosser/parallel_tests/wiki) says to split the cache by inserting
 ``config.cache_store = :file_store, Rails.root.join("tmp", "cache", "paralleltests#{ENV['TEST_ENV_NUMBER']}")`` on  ``environments/test.rb``
But zeus does not seems to reload the the environments file.

Is there any workaround for this problem?

**Comment by schneidmaster** [comment]
I will have to look into this. Normally, Zeus does not reload the environment at all (that's the whole point of it - it preloads everything) but there may be a way for this gem to override that/handle your case (which strikes me as a reasonably common one).

**Comment by layonferreira** [comment]
@schneidmaster thanks for the quick reply, if we change to ``config.cache_store = :memory_store``
It solves the problem.

**Comment by schneidmaster** [comment]
Great, that makes a lot of sense. I will add a note about that to the README. Closing this issue as that seems like an acceptable workaround.
