### ISSUE TITLE
Zeus Parallel Tests in Jenkins CI

### ISSUE THREAD

**Issue by bdfinlayson** [sevos/zeus-parallel_tests#39]
Is there a way to use this gem in a CI context, as on Jenkins? Currently it's required to have two terminal instances open (one for 'zeus start', and another for running something like 'zeus parallel_rspec spec'). How might I go about doing this on a service like Jenkins? Thanks!

**Comment by schneidmaster** [comment]
You might try daemonizing Zeus with something like [zeusd](https://github.com/veloper/zeusd). I'm not sure how up-to-date that gem is though. Alternatively, you could start Zeus in a [forked thread](https://github.com/sevos/zeus-parallel_tests/blob/master/spec/parallel_spec.rb#L8-L16) -- this is how we do CI on this repository.

**Comment by bdfinlayson** [comment]
Awesome. Thanks!
