### ISSUE TITLE
parallel_runtime_rspec.log incomplete

### ISSUE THREAD

**Issue by der-flo** [sevos/zeus-parallel_tests#42]
When running specs in parallel combined with zeus, the `parallel_runtime_rspec.log` is incomplete, some lines are missing.

So e. g. `bundle exec parallel_rspec spec/models` results in a complete file, `zeus parallel_rspec spec/models` in an incomplete one.

I'm using the most recent versions of the gems:
* parallel_tests: 2.14.1
* zeus-parallel_tests: 0.3.1
* zeus: 0.15.13

**Comment by der-flo** [comment]
I suspect the implementation of [Zeus::ParallelTests::Rails#spawn_slave](https://github.com/sevos/zeus-parallel_tests/blob/master/lib/zeus/parallel_tests/rails.rb#L89) is wrong regarding the setting of `ENV['TEST_ENV_NUMBER']`:

```ruby
ENV['TEST_ENV_NUMBER'] = test_env_number = (worker == '1' ? nil : worker)
```
The worker-1 case should return `''` instead of `nil`, at least [ParallelTests::RSpec::RuntimeLogger#start_dump](https://github.com/grosser/parallel_tests/blob/master/lib/parallel_tests/rspec/runtime_logger.rb#L36) expects this. The Readme also [mentions this](https://github.com/grosser/parallel_tests/blob/master/Readme.md#add-to-configdatabaseyml).

@sevos, @schneidmaster: Opinions?

**Comment by pboling** [comment]
I believe you are correct.  When `ENV['TEST_ENV_NUMBER']` is nil logic based on it assumes you are not running in parallel.  The fix is simple, and would be important for anything that needs to know if the spec suite is running in parallel (like logging).
